### ISSUE TITLE
Installation fails with ansible-2.4.1.0

### ISSUE THREAD

**Issue by gellner** [UKCloud/openshift-deployment-ansible#30]
The installation of 3.5 fails with ansible-2.4.1.0 - usually failing to pull/install/update etcd container early in the run.

Interestingly, version 3.6 installs fine with ansible-2.4.1.0

RH case 01974390 is open for this. Workaround to install 3.5 is to downgrade ansible:

```
sudo yum remove ansible-2.4.1.0-1.el7.noarch
sudo yum install -y ansible-2.4.0.0-5.el7.noarch atomic-openshift-utils atomic-openshift-excluder atomic-docker-excluder atomic-openshift-clients
```

**Comment by andywis** [comment]
Workaround in https://github.com/UKCloud/openshift-heat/pull/31 pins the Ansible version, so this bug does not occur.

**Comment by gellner** [comment]
This was fully resolved and the workaround removed a long while back in openshift-heat
