### ISSUE TITLE
Deprecated variables in 3.7

### ISSUE THREAD

**Issue by stevemul** [UKCloud/openshift-deployment-ansible#39]
Testing with 3.7 release of OpenShift has revealed the following warnings that will need addressed:

"[DEPRECATION WARNING]: openshift_hosted_metrics_deploy is a deprecated variable and will be no longer be used in the next minor release. Please update your inventory accordingly.",
"[DEPRECATION WARNING]: openshift_hosted_metrics_storage_kind is a deprecated variable and will be no longer be used in the next minor release. Please update your inventory accordingly."

**Comment by gellner** [comment]
No longer referenced in current code.
