### ISSUE TITLE
Initialisation playbook fails when 0 internet nodes deployed

### ISSUE THREAD

**Issue by stevemul** [UKCloud/openshift-deployment-ansible#73]
When no nodes are deployed that fit the internet_nodes criteria (e.g. workers that are internet facing and not infra nodes) the playbook fails to run successfully. This line needs to handle an empty array and do nothing if no nodes of this type are deployed.

https://github.com/UKCloud/openshift-deployment-ansible/blob/82c98f287c7695b263e150a321cc53aa345d5d9f/roles/initialisation/templates/ansible-hosts-multimaster.j2#L196

**Comment by gellner** [comment]
Looks like https://github.com/UKCloud/openshift-deployment-ansible/pull/77 closed this issue.
